import { beforeAll, describe, expect, it, vi } from 'vitest';
import { memoryCache } from '../testing/memory-cache';
import {
	CALENDAR_SCOPE,
	getAccessToken,
	mintAccessToken,
	readServiceAccountCredentials,
	signAssertion,
	type ServiceAccountCredentials
} from './sa-token';

/**
 * The M5.2 done-condition, plus the two things about this credential that are
 * easy to get wrong and impossible to notice: that the PEM arrives with
 * literal backslash-n rather than newlines, and that the placeholder in
 * `.dev.vars` is PEM-shaped.
 *
 * The key below is a real RSA-2048 keypair generated by WebCrypto, and the
 * assertion is verified with its public half — so this proves the signature
 * Google would check, not just that some bytes came out of `crypto.subtle`.
 */

/** The shape `.dev.vars` and `wrangler secret put` actually deliver. */
let escapedPem: string;
let publicKey: CryptoKey;
let credentials: ServiceAccountCredentials;

const CLIENT_EMAIL = 'calendar-reader@personal-site.iam.gserviceaccount.com';

beforeAll(async () => {
	const pair = (await crypto.subtle.generateKey(
		{
			name: 'RSASSA-PKCS1-v1_5',
			modulusLength: 2048,
			publicExponent: new Uint8Array([1, 0, 1]),
			hash: 'SHA-256'
		},
		true,
		['sign', 'verify']
	)) as CryptoKeyPair;

	const pkcs8 = new Uint8Array(await crypto.subtle.exportKey('pkcs8', pair.privateKey));
	const base64 = btoa(String.fromCharCode(...pkcs8));
	escapedPem = [
		'-----BEGIN PRIVATE KEY-----',
		...(base64.match(/.{1,64}/g) ?? []),
		'-----END PRIVATE KEY-----',
		''
	].join('\\n');

	publicKey = pair.publicKey;
	credentials = { clientEmail: CLIENT_EMAIL, privateKeyPem: escapedPem };
});

function fromBase64url(value: string): Uint8Array<ArrayBuffer> {
	const base64 = value
		.replaceAll('-', '+')
		.replaceAll('_', '/')
		.padEnd(value.length + ((4 - (value.length % 4)) % 4), '=');
	return Uint8Array.from(atob(base64), (character) => character.charCodeAt(0));
}

const decodeJson = (segment: string) =>
	JSON.parse(new TextDecoder().decode(fromBase64url(segment)));

/** A token endpoint that records what it was asked for and how often. */
function tokenEndpoint(token = 'ya29.test-access-token') {
	const requests: { url: string; body: string }[] = [];

	const fetchImpl = vi.fn(async (input: RequestInfo | URL, init?: RequestInit) => {
		requests.push({ url: String(input), body: String(init?.body ?? '') });
		return new Response(JSON.stringify({ access_token: token, expires_in: 3600 }), {
			headers: { 'content-type': 'application/json' }
		});
	});

	return { fetchImpl, requests };
}

describe('readServiceAccountCredentials', () => {
	const realKey = () => 'x'.repeat(1600);

	it('accepts a service-account email and a full-length PEM', () => {
		const env = {
			GOOGLE_SA_EMAIL: CLIENT_EMAIL,
			GOOGLE_SA_PRIVATE_KEY: `-----BEGIN PRIVATE KEY-----\\n${realKey()}\\n-----END PRIVATE KEY-----\\n`
		} as Partial<Env>;

		expect(readServiceAccountCredentials(env)?.clientEmail).toBe(CLIENT_EMAIL);
	});

	/**
	 * The placeholder that sat in `.dev.vars` through M4 carries the armour and
	 * is ~70 characters. "Is it non-empty" passes on it; only the length check
	 * catches it. See HANDOFF.md.
	 */
	it('rejects the PEM-shaped placeholder, which is far too short to be a key', () => {
		const env = {
			GOOGLE_SA_EMAIL: CLIENT_EMAIL,
			GOOGLE_SA_PRIVATE_KEY:
				'-----BEGIN PRIVATE KEY-----\\nreplace-me\\n-----END PRIVATE KEY-----\\n'
		} as Partial<Env>;

		expect(readServiceAccountCredentials(env)).toBeNull();
	});

	it('rejects an address that is not a service account, and a missing env', () => {
		expect(
			readServiceAccountCredentials({
				GOOGLE_SA_EMAIL: 'caden@gmail.com',
				GOOGLE_SA_PRIVATE_KEY: `-----BEGIN PRIVATE KEY-----\\n${realKey()}\\n-----END PRIVATE KEY-----`
			} as Partial<Env>)
		).toBeNull();
		expect(readServiceAccountCredentials(undefined)).toBeNull();
	});

	it('rejects a key that is long but is not a PEM', () => {
		expect(
			readServiceAccountCredentials({
				GOOGLE_SA_EMAIL: CLIENT_EMAIL,
				GOOGLE_SA_PRIVATE_KEY: realKey()
			} as Partial<Env>)
		).toBeNull();
	});
});

describe('signAssertion', () => {
	it('builds the claim set plan §4 specifies', async () => {
		const issuedAt = 1_770_000_000;
		const [header, claims] = (await signAssertion(credentials, issuedAt)).split('.');

		expect(decodeJson(header)).toEqual({ alg: 'RS256', typ: 'JWT' });
		expect(decodeJson(claims)).toEqual({
			iss: CLIENT_EMAIL,
			scope: CALENDAR_SCOPE,
			aud: 'https://oauth2.googleapis.com/token',
			iat: issuedAt,
			exp: issuedAt + 3600
		});
	});

	/**
	 * The `\\n` replacement is the whole test. Without it the base64 body still
	 * decodes — whitespace is stripped either way — but the armour runs into it
	 * and `importKey` gets garbage DER.
	 */
	it('signs verifiably with a PEM whose newlines are literal backslash-n', async () => {
		const assertion = await signAssertion(credentials, 1_770_000_000);
		const [header, claims, signature] = assertion.split('.');

		const verified = await crypto.subtle.verify(
			'RSASSA-PKCS1-v1_5',
			publicKey,
			fromBase64url(signature),
			new TextEncoder().encode(`${header}.${claims}`)
		);

		expect(verified).toBe(true);
	});

	it('refuses a PEM whose body is not base64', async () => {
		await expect(
			signAssertion(
				{ clientEmail: CLIENT_EMAIL, privateKeyPem: '-----BEGIN PRIVATE KEY-----\\n!!!!\\n' },
				0
			)
		).rejects.toThrow(/base64/);
	});
});

describe('mintAccessToken', () => {
	it('posts the jwt-bearer grant and returns the access token', async () => {
		const { fetchImpl, requests } = tokenEndpoint();

		expect(await mintAccessToken(credentials, { fetch: fetchImpl, now: 0 })).toBe(
			'ya29.test-access-token'
		);

		expect(requests[0].url).toBe('https://oauth2.googleapis.com/token');
		expect(requests[0].body).toContain(
			`grant_type=${encodeURIComponent('urn:ietf:params:oauth:grant-type:jwt-bearer')}`
		);
		expect(requests[0].body).toContain('assertion=');
	});

	it('throws on a non-2xx without quoting the body back', async () => {
		const fetchImpl = vi.fn(
			async () => new Response('the assertion was rejected', { status: 400 })
		);

		await expect(mintAccessToken(credentials, { fetch: fetchImpl })).rejects.toThrow(
			'google: the token endpoint answered 400.'
		);
	});

	it('throws when the response carries no access_token', async () => {
		const fetchImpl = vi.fn(
			async () => new Response(JSON.stringify({ expires_in: 3600 }), { status: 200 })
		);

		await expect(mintAccessToken(credentials, { fetch: fetchImpl })).rejects.toThrow(
			/no access_token/
		);
	});
});

describe('getAccessToken', () => {
	/** The M5.2 done-condition. */
	it('mints once for two calls inside the cache window', async () => {
		const { fetchImpl } = tokenEndpoint();
		const cache = memoryCache();

		const first = await getAccessToken({ credentials, cache, fetch: fetchImpl });
		const second = await getAccessToken({ credentials, cache, fetch: fetchImpl });

		expect(first).toBe(second);
		expect(fetchImpl).toHaveBeenCalledTimes(1);
	});

	it('mints again once the 55-minute entry has expired', async () => {
		const { fetchImpl } = tokenEndpoint();
		let clock = 0;
		const cache = memoryCache(() => clock);

		await getAccessToken({ credentials, cache, fetch: fetchImpl });
		clock = 55 * 60 * 1000 + 1;
		await getAccessToken({ credentials, cache, fetch: fetchImpl });

		expect(fetchImpl).toHaveBeenCalledTimes(2);
	});

	it('mints per call when there is no Cache API, as under vite dev', async () => {
		const { fetchImpl } = tokenEndpoint();

		await getAccessToken({ credentials, cache: null, fetch: fetchImpl });
		await getAccessToken({ credentials, cache: null, fetch: fetchImpl });

		expect(fetchImpl).toHaveBeenCalledTimes(2);
	});
});
